### ISSUE TITLE
Change currency on Google Flight

### ISSUE THREAD

**Issue by DebianRoxx** [StephanMc/extension-restore-google-maps#1]
Hi,

Thanks for your extension but I have seen that it change currency on [Google Flight](https://www.google.com/travel/flights) too.
Can you exclude this site please ?

Thanks,
Sylvain

**Comment by StephanMc** [comment]
Hi Sylvain, 
Thank you for reporting, I can confirm the issue indeed. Will work on a fix probably tomorrow and will let you know. 
Best,
Stephane

**Comment by StephanMc** [comment]
Hi @DebianRoxx ,

A fix has been published, hopefully it would be globally available in a few hours as version 1.0.4 .
Will close the issue once you'll confirm it working properly on your side.

Thanks,
Stéphane

**Comment by DebianRoxx** [comment]
Hi,

I confirm that it's works great !

Thanks,
Sylvain

**Comment by DebianRoxx** [comment]
Hi,

I confirm that it's works great !

Thanks,
Sylvain
