### ISSUE TITLE
[BUG] Does not render google maps web results correctly

### ISSUE THREAD

**Issue by jogerj** [StephanMc/extension-restore-google-maps#4]
I've isolated the culprit to be this extension

Reproduction steps:
1. [Open a location on google maps](https://www.google.com/maps/place/Newark+Liberty+International+Airport/@40.7755395,-72.3199463,268347m/data=!3m1!1e3!4m15!1m8!3m7!1s0x89c24fa5d33f083b:0xc80b8f06e177fe62!2sNew+York,+NY,+USA!3b1!8m2!3d40.7127753!4d-74.0059728!16zL20vMDJfMjg2!3m5!1s0x89c252e1c5ec0cef:0xb3f3b437c5d7f286!8m2!3d40.6895314!4d-74.1744624!16zL20vMDFsNWht?entry=ttu&g_ep=EgoyMDI0MTEyNC4xIKXMDSoASAFQAw%3D%3D)
2. Scroll down until web results appear
3. Web result appears in full width of the screen

Actual result:
![image](https://github.com/user-attachments/assets/85c8cdd0-1ce1-4487-b32e-d9112c73aa62)

Expected result:
![image](https://github.com/user-attachments/assets/2d05e9ff-0fe9-4998-bb81-cc14584cf854)

**Comment by jogerj** [comment]
In any case, I switched to using this extension. It's a cleaner approach without side effects

https://github.com/mrakowski0/readd-gmaps-links-chrome-extension
https://chromewebstore.google.com/detail/re-introduce-google-maps/mjkkdbmdflkcjmonelmlokplkgnjcnji

**Comment by StephanMc** [comment]
Hi,
Can you please provide a video to reproduce the issue ? Cause I don't experience this even in a clear environment.
The extension has not access to Maps website so something else should be wrong here. I'd be glad to help if needed.


However, it is _very_ unappropriate to provide another 'similar' software link without even waiting for an answer. Such behaviors won't be tolerated, and therefore, I'll close this issue.  Feel free to open it when you have a valid evidence, like a video recording a private session of your browser without any other extension than this one.

I'll let your comment visible to anyone, and add also a screenshot (of just before your edited comment) just in case. 
![image](https://github.com/user-attachments/assets/d0f14240-b171-44f0-94b0-b4b028aa0564)
